name: Build & Release Bitwarden Custom APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.BW_GITHUB_PAT }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup JDK-21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Create user.properties
        run: |
          cat > user.properties <<EOF
          gitHubUser=${{ github.actor }}
          gitHubToken=${{ secrets.BW_GITHUB_PAT }}
          localSdk=false
          EOF

      - name: Gradle assembleFdroidDebug
        run: |
          chmod +x ./gradlew
          ./gradlew app:assembleFdroidDebug --no-build-cache --stacktrace

      - name: Save APK to variable
        id: apk_file
        run: |
          APK=$(ls app/build/outputs/apk/fdroid/debug/*.apk)
          echo "APK=$APK" >> $GITHUB_ENV

      - name: Upload build artifact(workflow artifact)
        uses: actions/upload-artifact@v4
        with:
          name: bitwarden-custom-apk
          path: ${{ env.APK }}

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: ${{ env.APK }}

